endpoints:
  - target_host: github.com
    target_type: https
    target_port: 443
    source_type: http
    source_port: 17080
    health: /healthz
  - target_host: generativelanguage.googleapis.com
    target_port: 443
    source_port: 14530
    source_type: http
    target_type: https
    health: /healthz
    redact_request_headers:
      - X-Goog-Api-Key
      - Authorization
      - X-Goog-User-Project
      - User-Agent
      - X-Goog-Api-Client
    response_header_replacements:
      - header: X-Goog-Upload-Url
        regex: "^https://generativelanguage.googleapis.com/"
        replace: "http://localhost:14530/"
